/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as PrivacyPolicyRouteImport } from './routes/privacy-policy'
import { Route as TermsConditionsRouteImport } from './routes/terms-conditions'
import { Route as ProjectsIdRouteImport } from './routes/projects.$id'
import { Route as ProjectsFarmlandDevelopmentRouteImport } from './routes/projects.farmland-development'
import { Route as ProjectsPlottedDevelopmentRouteImport } from './routes/projects.plotted-development'
import { Route as ServicesArchitecturalPlanningRouteImport } from './routes/services.architectural-planning'
import { Route as ServicesCompoundWallConstructionRouteImport } from './routes/services.compound-wall-construction'
import { Route as ServicesElectricalInfrastructureRouteImport } from './routes/services.electrical-infrastructure'
import { Route as ServicesEndToEndLandDevelopmentRouteImport } from './routes/services.end-to-end-land-development'
import { Route as ServicesEntranceArchDesignConstructionRouteImport } from './routes/services.entrance-arch-design-construction'
import { Route as ServicesFarmlandDevelopmentRouteImport } from './routes/services.farmland-development'
import { Route as ServicesFootpathPaverInstallationRouteImport } from './routes/services.footpath-paver-installation'
import { Route as ServicesInternalRoadsRouteImport } from './routes/services.internal-roads'
import { Route as ServicesLandLevelingSitePreparationRouteImport } from './routes/services.land-leveling-site-preparation'
import { Route as ServicesLandscapeTreePlantationRouteImport } from './routes/services.landscape-tree-plantation'
import { Route as ServicesParkDevelopmentRouteImport } from './routes/services.park-development'
import { Route as ServicesPlottedDevelopmentRouteImport } from './routes/services.plotted-development'
import { Route as ServicesRccDrainageWorksRouteImport } from './routes/services.rcc-drainage-works'
import { Route as ServicesRoadDevelopmentWorksRouteImport } from './routes/services.road-development-works'
import { Route as ServicesSiteIdentificationWorksRouteImport } from './routes/services.site-identification-works'
import { Route as ServicesSiteSurveyLayoutExecutionRouteImport } from './routes/services.site-survey-layout-execution'
import { Route as ServicesStormWaterDrainageRouteImport } from './routes/services.storm-water-drainage'
import { Route as ServicesTreePlantationLandscapingRouteImport } from './routes/services.tree-plantation-landscaping'
import { Route as ServicesUndergroundSewerageUgdWorksRouteImport } from './routes/services.underground-sewerage-ugd-works'
import { Route as ServicesWaterPipelineNetworksRouteImport } from './routes/services.water-pipeline-networks'
import { Route as ServicesWaterSupplyLineInstallationRouteImport } from './routes/services.water-supply-line-installation'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyPolicyRoute = PrivacyPolicyRouteImport.update({
  id: '/privacy-policy',
  path: '/privacy-policy',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsConditionsRoute = TermsConditionsRouteImport.update({
  id: '/terms-conditions',
  path: '/terms-conditions',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsIdRoute = ProjectsIdRouteImport.update({
  id: '/projects/$id',
  path: '/projects/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsFarmlandDevelopmentRoute =
  ProjectsFarmlandDevelopmentRouteImport.update({
    id: '/projects/farmland-development',
    path: '/projects/farmland-development',
    getParentRoute: () => rootRouteImport,
  } as any)
const ProjectsPlottedDevelopmentRoute =
  ProjectsPlottedDevelopmentRouteImport.update({
    id: '/projects/plotted-development',
    path: '/projects/plotted-development',
    getParentRoute: () => rootRouteImport,
  } as any)
const ServicesArchitecturalPlanningRoute =
  ServicesArchitecturalPlanningRouteImport.update({
    id: '/services/architectural-planning',
    path: '/services/architectural-planning',
    getParentRoute: () => rootRouteImport,
  } as any)
const ServicesCompoundWallConstructionRoute =
  ServicesCompoundWallConstructionRouteImport.update({
    id: '/services/compound-wall-construction',
    path: '/services/compound-wall-construction',
    getParentRoute: () => rootRouteImport,
  } as any)
const ServicesElectricalInfrastructureRoute =
  ServicesElectricalInfrastructureRouteImport.update({
    id: '/services/electrical-infrastructure',
    path: '/services/electrical-infrastructure',
    getParentRoute: () => rootRouteImport,
  } as any)
const ServicesEndToEndLandDevelopmentRoute =
  ServicesEndToEndLandDevelopmentRouteImport.update({
    id: '/services/end-to-end-land-development',
    path: '/services/end-to-end-land-development',
    getParentRoute: () => rootRouteImport,
  } as any)
const ServicesEntranceArchDesignConstructionRoute =
  ServicesEntranceArchDesignConstructionRouteImport.update({
    id: '/services/entrance-arch-design-construction',
    path: '/services/entrance-arch-design-construction',
    getParentRoute: () => rootRouteImport,
  } as any)
const ServicesFarmlandDevelopmentRoute =
  ServicesFarmlandDevelopmentRouteImport.update({
    id: '/services/farmland-development',
    path: '/services/farmland-development',
    getParentRoute: () => rootRouteImport,
  } as any)
const ServicesFootpathPaverInstallationRoute =
  ServicesFootpathPaverInstallationRouteImport.update({
    id: '/services/footpath-paver-installation',
    path: '/services/footpath-paver-installation',
    getParentRoute: () => rootRouteImport,
  } as any)
const ServicesInternalRoadsRoute = ServicesInternalRoadsRouteImport.update({
  id: '/services/internal-roads',
  path: '/services/internal-roads',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesLandLevelingSitePreparationRoute =
  ServicesLandLevelingSitePreparationRouteImport.update({
    id: '/services/land-leveling-site-preparation',
    path: '/services/land-leveling-site-preparation',
    getParentRoute: () => rootRouteImport,
  } as any)
const ServicesLandscapeTreePlantationRoute =
  ServicesLandscapeTreePlantationRouteImport.update({
    id: '/services/landscape-tree-plantation',
    path: '/services/landscape-tree-plantation',
    getParentRoute: () => rootRouteImport,
  } as any)
const ServicesParkDevelopmentRoute = ServicesParkDevelopmentRouteImport.update({
  id: '/services/park-development',
  path: '/services/park-development',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesPlottedDevelopmentRoute =
  ServicesPlottedDevelopmentRouteImport.update({
    id: '/services/plotted-development',
    path: '/services/plotted-development',
    getParentRoute: () => rootRouteImport,
  } as any)
const ServicesRccDrainageWorksRoute =
  ServicesRccDrainageWorksRouteImport.update({
    id: '/services/rcc-drainage-works',
    path: '/services/rcc-drainage-works',
    getParentRoute: () => rootRouteImport,
  } as any)
const ServicesRoadDevelopmentWorksRoute =
  ServicesRoadDevelopmentWorksRouteImport.update({
    id: '/services/road-development-works',
    path: '/services/road-development-works',
    getParentRoute: () => rootRouteImport,
  } as any)
const ServicesSiteIdentificationWorksRoute =
  ServicesSiteIdentificationWorksRouteImport.update({
    id: '/services/site-identification-works',
    path: '/services/site-identification-works',
    getParentRoute: () => rootRouteImport,
  } as any)
const ServicesSiteSurveyLayoutExecutionRoute =
  ServicesSiteSurveyLayoutExecutionRouteImport.update({
    id: '/services/site-survey-layout-execution',
    path: '/services/site-survey-layout-execution',
    getParentRoute: () => rootRouteImport,
  } as any)
const ServicesStormWaterDrainageRoute =
  ServicesStormWaterDrainageRouteImport.update({
    id: '/services/storm-water-drainage',
    path: '/services/storm-water-drainage',
    getParentRoute: () => rootRouteImport,
  } as any)
const ServicesTreePlantationLandscapingRoute =
  ServicesTreePlantationLandscapingRouteImport.update({
    id: '/services/tree-plantation-landscaping',
    path: '/services/tree-plantation-landscaping',
    getParentRoute: () => rootRouteImport,
  } as any)
const ServicesUndergroundSewerageUgdWorksRoute =
  ServicesUndergroundSewerageUgdWorksRouteImport.update({
    id: '/services/underground-sewerage-ugd-works',
    path: '/services/underground-sewerage-ugd-works',
    getParentRoute: () => rootRouteImport,
  } as any)
const ServicesWaterPipelineNetworksRoute =
  ServicesWaterPipelineNetworksRouteImport.update({
    id: '/services/water-pipeline-networks',
    path: '/services/water-pipeline-networks',
    getParentRoute: () => rootRouteImport,
  } as any)
const ServicesWaterSupplyLineInstallationRoute =
  ServicesWaterSupplyLineInstallationRouteImport.update({
    id: '/services/water-supply-line-installation',
    path: '/services/water-supply-line-installation',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/terms-conditions': typeof TermsConditionsRoute
  '/projects/$id': typeof ProjectsIdRoute
  '/projects/farmland-development': typeof ProjectsFarmlandDevelopmentRoute
  '/projects/plotted-development': typeof ProjectsPlottedDevelopmentRoute
  '/services/architectural-planning': typeof ServicesArchitecturalPlanningRoute
  '/services/compound-wall-construction': typeof ServicesCompoundWallConstructionRoute
  '/services/electrical-infrastructure': typeof ServicesElectricalInfrastructureRoute
  '/services/end-to-end-land-development': typeof ServicesEndToEndLandDevelopmentRoute
  '/services/entrance-arch-design-construction': typeof ServicesEntranceArchDesignConstructionRoute
  '/services/farmland-development': typeof ServicesFarmlandDevelopmentRoute
  '/services/footpath-paver-installation': typeof ServicesFootpathPaverInstallationRoute
  '/services/internal-roads': typeof ServicesInternalRoadsRoute
  '/services/land-leveling-site-preparation': typeof ServicesLandLevelingSitePreparationRoute
  '/services/landscape-tree-plantation': typeof ServicesLandscapeTreePlantationRoute
  '/services/park-development': typeof ServicesParkDevelopmentRoute
  '/services/plotted-development': typeof ServicesPlottedDevelopmentRoute
  '/services/rcc-drainage-works': typeof ServicesRccDrainageWorksRoute
  '/services/road-development-works': typeof ServicesRoadDevelopmentWorksRoute
  '/services/site-identification-works': typeof ServicesSiteIdentificationWorksRoute
  '/services/site-survey-layout-execution': typeof ServicesSiteSurveyLayoutExecutionRoute
  '/services/storm-water-drainage': typeof ServicesStormWaterDrainageRoute
  '/services/tree-plantation-landscaping': typeof ServicesTreePlantationLandscapingRoute
  '/services/underground-sewerage-ugd-works': typeof ServicesUndergroundSewerageUgdWorksRoute
  '/services/water-pipeline-networks': typeof ServicesWaterPipelineNetworksRoute
  '/services/water-supply-line-installation': typeof ServicesWaterSupplyLineInstallationRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/terms-conditions': typeof TermsConditionsRoute
  '/projects/$id': typeof ProjectsIdRoute
  '/projects/farmland-development': typeof ProjectsFarmlandDevelopmentRoute
  '/projects/plotted-development': typeof ProjectsPlottedDevelopmentRoute
  '/services/architectural-planning': typeof ServicesArchitecturalPlanningRoute
  '/services/compound-wall-construction': typeof ServicesCompoundWallConstructionRoute
  '/services/electrical-infrastructure': typeof ServicesElectricalInfrastructureRoute
  '/services/end-to-end-land-development': typeof ServicesEndToEndLandDevelopmentRoute
  '/services/entrance-arch-design-construction': typeof ServicesEntranceArchDesignConstructionRoute
  '/services/farmland-development': typeof ServicesFarmlandDevelopmentRoute
  '/services/footpath-paver-installation': typeof ServicesFootpathPaverInstallationRoute
  '/services/internal-roads': typeof ServicesInternalRoadsRoute
  '/services/land-leveling-site-preparation': typeof ServicesLandLevelingSitePreparationRoute
  '/services/landscape-tree-plantation': typeof ServicesLandscapeTreePlantationRoute
  '/services/park-development': typeof ServicesParkDevelopmentRoute
  '/services/plotted-development': typeof ServicesPlottedDevelopmentRoute
  '/services/rcc-drainage-works': typeof ServicesRccDrainageWorksRoute
  '/services/road-development-works': typeof ServicesRoadDevelopmentWorksRoute
  '/services/site-identification-works': typeof ServicesSiteIdentificationWorksRoute
  '/services/site-survey-layout-execution': typeof ServicesSiteSurveyLayoutExecutionRoute
  '/services/storm-water-drainage': typeof ServicesStormWaterDrainageRoute
  '/services/tree-plantation-landscaping': typeof ServicesTreePlantationLandscapingRoute
  '/services/underground-sewerage-ugd-works': typeof ServicesUndergroundSewerageUgdWorksRoute
  '/services/water-pipeline-networks': typeof ServicesWaterPipelineNetworksRoute
  '/services/water-supply-line-installation': typeof ServicesWaterSupplyLineInstallationRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/terms-conditions': typeof TermsConditionsRoute
  '/projects/$id': typeof ProjectsIdRoute
  '/projects/farmland-development': typeof ProjectsFarmlandDevelopmentRoute
  '/projects/plotted-development': typeof ProjectsPlottedDevelopmentRoute
  '/services/architectural-planning': typeof ServicesArchitecturalPlanningRoute
  '/services/compound-wall-construction': typeof ServicesCompoundWallConstructionRoute
  '/services/electrical-infrastructure': typeof ServicesElectricalInfrastructureRoute
  '/services/end-to-end-land-development': typeof ServicesEndToEndLandDevelopmentRoute
  '/services/entrance-arch-design-construction': typeof ServicesEntranceArchDesignConstructionRoute
  '/services/farmland-development': typeof ServicesFarmlandDevelopmentRoute
  '/services/footpath-paver-installation': typeof ServicesFootpathPaverInstallationRoute
  '/services/internal-roads': typeof ServicesInternalRoadsRoute
  '/services/land-leveling-site-preparation': typeof ServicesLandLevelingSitePreparationRoute
  '/services/landscape-tree-plantation': typeof ServicesLandscapeTreePlantationRoute
  '/services/park-development': typeof ServicesParkDevelopmentRoute
  '/services/plotted-development': typeof ServicesPlottedDevelopmentRoute
  '/services/rcc-drainage-works': typeof ServicesRccDrainageWorksRoute
  '/services/road-development-works': typeof ServicesRoadDevelopmentWorksRoute
  '/services/site-identification-works': typeof ServicesSiteIdentificationWorksRoute
  '/services/site-survey-layout-execution': typeof ServicesSiteSurveyLayoutExecutionRoute
  '/services/storm-water-drainage': typeof ServicesStormWaterDrainageRoute
  '/services/tree-plantation-landscaping': typeof ServicesTreePlantationLandscapingRoute
  '/services/underground-sewerage-ugd-works': typeof ServicesUndergroundSewerageUgdWorksRoute
  '/services/water-pipeline-networks': typeof ServicesWaterPipelineNetworksRoute
  '/services/water-supply-line-installation': typeof ServicesWaterSupplyLineInstallationRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/privacy-policy'
    | '/terms-conditions'
    | '/projects/$id'
    | '/projects/farmland-development'
    | '/projects/plotted-development'
    | '/services/architectural-planning'
    | '/services/compound-wall-construction'
    | '/services/electrical-infrastructure'
    | '/services/end-to-end-land-development'
    | '/services/entrance-arch-design-construction'
    | '/services/farmland-development'
    | '/services/footpath-paver-installation'
    | '/services/internal-roads'
    | '/services/land-leveling-site-preparation'
    | '/services/landscape-tree-plantation'
    | '/services/park-development'
    | '/services/plotted-development'
    | '/services/rcc-drainage-works'
    | '/services/road-development-works'
    | '/services/site-identification-works'
    | '/services/site-survey-layout-execution'
    | '/services/storm-water-drainage'
    | '/services/tree-plantation-landscaping'
    | '/services/underground-sewerage-ugd-works'
    | '/services/water-pipeline-networks'
    | '/services/water-supply-line-installation'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/privacy-policy'
    | '/terms-conditions'
    | '/projects/$id'
    | '/projects/farmland-development'
    | '/projects/plotted-development'
    | '/services/architectural-planning'
    | '/services/compound-wall-construction'
    | '/services/electrical-infrastructure'
    | '/services/end-to-end-land-development'
    | '/services/entrance-arch-design-construction'
    | '/services/farmland-development'
    | '/services/footpath-paver-installation'
    | '/services/internal-roads'
    | '/services/land-leveling-site-preparation'
    | '/services/landscape-tree-plantation'
    | '/services/park-development'
    | '/services/plotted-development'
    | '/services/rcc-drainage-works'
    | '/services/road-development-works'
    | '/services/site-identification-works'
    | '/services/site-survey-layout-execution'
    | '/services/storm-water-drainage'
    | '/services/tree-plantation-landscaping'
    | '/services/underground-sewerage-ugd-works'
    | '/services/water-pipeline-networks'
    | '/services/water-supply-line-installation'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/privacy-policy'
    | '/terms-conditions'
    | '/projects/$id'
    | '/projects/farmland-development'
    | '/projects/plotted-development'
    | '/services/architectural-planning'
    | '/services/compound-wall-construction'
    | '/services/electrical-infrastructure'
    | '/services/end-to-end-land-development'
    | '/services/entrance-arch-design-construction'
    | '/services/farmland-development'
    | '/services/footpath-paver-installation'
    | '/services/internal-roads'
    | '/services/land-leveling-site-preparation'
    | '/services/landscape-tree-plantation'
    | '/services/park-development'
    | '/services/plotted-development'
    | '/services/rcc-drainage-works'
    | '/services/road-development-works'
    | '/services/site-identification-works'
    | '/services/site-survey-layout-execution'
    | '/services/storm-water-drainage'
    | '/services/tree-plantation-landscaping'
    | '/services/underground-sewerage-ugd-works'
    | '/services/water-pipeline-networks'
    | '/services/water-supply-line-installation'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  PrivacyPolicyRoute: typeof PrivacyPolicyRoute
  TermsConditionsRoute: typeof TermsConditionsRoute
  ProjectsIdRoute: typeof ProjectsIdRoute
  ProjectsFarmlandDevelopmentRoute: typeof ProjectsFarmlandDevelopmentRoute
  ProjectsPlottedDevelopmentRoute: typeof ProjectsPlottedDevelopmentRoute
  ServicesArchitecturalPlanningRoute: typeof ServicesArchitecturalPlanningRoute
  ServicesCompoundWallConstructionRoute: typeof ServicesCompoundWallConstructionRoute
  ServicesElectricalInfrastructureRoute: typeof ServicesElectricalInfrastructureRoute
  ServicesEndToEndLandDevelopmentRoute: typeof ServicesEndToEndLandDevelopmentRoute
  ServicesEntranceArchDesignConstructionRoute: typeof ServicesEntranceArchDesignConstructionRoute
  ServicesFarmlandDevelopmentRoute: typeof ServicesFarmlandDevelopmentRoute
  ServicesFootpathPaverInstallationRoute: typeof ServicesFootpathPaverInstallationRoute
  ServicesInternalRoadsRoute: typeof ServicesInternalRoadsRoute
  ServicesLandLevelingSitePreparationRoute: typeof ServicesLandLevelingSitePreparationRoute
  ServicesLandscapeTreePlantationRoute: typeof ServicesLandscapeTreePlantationRoute
  ServicesParkDevelopmentRoute: typeof ServicesParkDevelopmentRoute
  ServicesPlottedDevelopmentRoute: typeof ServicesPlottedDevelopmentRoute
  ServicesRccDrainageWorksRoute: typeof ServicesRccDrainageWorksRoute
  ServicesRoadDevelopmentWorksRoute: typeof ServicesRoadDevelopmentWorksRoute
  ServicesSiteIdentificationWorksRoute: typeof ServicesSiteIdentificationWorksRoute
  ServicesSiteSurveyLayoutExecutionRoute: typeof ServicesSiteSurveyLayoutExecutionRoute
  ServicesStormWaterDrainageRoute: typeof ServicesStormWaterDrainageRoute
  ServicesTreePlantationLandscapingRoute: typeof ServicesTreePlantationLandscapingRoute
  ServicesUndergroundSewerageUgdWorksRoute: typeof ServicesUndergroundSewerageUgdWorksRoute
  ServicesWaterPipelineNetworksRoute: typeof ServicesWaterPipelineNetworksRoute
  ServicesWaterSupplyLineInstallationRoute: typeof ServicesWaterSupplyLineInstallationRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy-policy': {
      id: '/privacy-policy'
      path: '/privacy-policy'
      fullPath: '/privacy-policy'
      preLoaderRoute: typeof PrivacyPolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms-conditions': {
      id: '/terms-conditions'
      path: '/terms-conditions'
      fullPath: '/terms-conditions'
      preLoaderRoute: typeof TermsConditionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/$id': {
      id: '/projects/$id'
      path: '/projects/$id'
      fullPath: '/projects/$id'
      preLoaderRoute: typeof ProjectsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/farmland-development': {
      id: '/projects/farmland-development'
      path: '/projects/farmland-development'
      fullPath: '/projects/farmland-development'
      preLoaderRoute: typeof ProjectsFarmlandDevelopmentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/plotted-development': {
      id: '/projects/plotted-development'
      path: '/projects/plotted-development'
      fullPath: '/projects/plotted-development'
      preLoaderRoute: typeof ProjectsPlottedDevelopmentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/architectural-planning': {
      id: '/services/architectural-planning'
      path: '/services/architectural-planning'
      fullPath: '/services/architectural-planning'
      preLoaderRoute: typeof ServicesArchitecturalPlanningRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/compound-wall-construction': {
      id: '/services/compound-wall-construction'
      path: '/services/compound-wall-construction'
      fullPath: '/services/compound-wall-construction'
      preLoaderRoute: typeof ServicesCompoundWallConstructionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/electrical-infrastructure': {
      id: '/services/electrical-infrastructure'
      path: '/services/electrical-infrastructure'
      fullPath: '/services/electrical-infrastructure'
      preLoaderRoute: typeof ServicesElectricalInfrastructureRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/end-to-end-land-development': {
      id: '/services/end-to-end-land-development'
      path: '/services/end-to-end-land-development'
      fullPath: '/services/end-to-end-land-development'
      preLoaderRoute: typeof ServicesEndToEndLandDevelopmentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/entrance-arch-design-construction': {
      id: '/services/entrance-arch-design-construction'
      path: '/services/entrance-arch-design-construction'
      fullPath: '/services/entrance-arch-design-construction'
      preLoaderRoute: typeof ServicesEntranceArchDesignConstructionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/farmland-development': {
      id: '/services/farmland-development'
      path: '/services/farmland-development'
      fullPath: '/services/farmland-development'
      preLoaderRoute: typeof ServicesFarmlandDevelopmentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/footpath-paver-installation': {
      id: '/services/footpath-paver-installation'
      path: '/services/footpath-paver-installation'
      fullPath: '/services/footpath-paver-installation'
      preLoaderRoute: typeof ServicesFootpathPaverInstallationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/internal-roads': {
      id: '/services/internal-roads'
      path: '/services/internal-roads'
      fullPath: '/services/internal-roads'
      preLoaderRoute: typeof ServicesInternalRoadsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/land-leveling-site-preparation': {
      id: '/services/land-leveling-site-preparation'
      path: '/services/land-leveling-site-preparation'
      fullPath: '/services/land-leveling-site-preparation'
      preLoaderRoute: typeof ServicesLandLevelingSitePreparationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/landscape-tree-plantation': {
      id: '/services/landscape-tree-plantation'
      path: '/services/landscape-tree-plantation'
      fullPath: '/services/landscape-tree-plantation'
      preLoaderRoute: typeof ServicesLandscapeTreePlantationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/park-development': {
      id: '/services/park-development'
      path: '/services/park-development'
      fullPath: '/services/park-development'
      preLoaderRoute: typeof ServicesParkDevelopmentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/plotted-development': {
      id: '/services/plotted-development'
      path: '/services/plotted-development'
      fullPath: '/services/plotted-development'
      preLoaderRoute: typeof ServicesPlottedDevelopmentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/rcc-drainage-works': {
      id: '/services/rcc-drainage-works'
      path: '/services/rcc-drainage-works'
      fullPath: '/services/rcc-drainage-works'
      preLoaderRoute: typeof ServicesRccDrainageWorksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/road-development-works': {
      id: '/services/road-development-works'
      path: '/services/road-development-works'
      fullPath: '/services/road-development-works'
      preLoaderRoute: typeof ServicesRoadDevelopmentWorksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/site-identification-works': {
      id: '/services/site-identification-works'
      path: '/services/site-identification-works'
      fullPath: '/services/site-identification-works'
      preLoaderRoute: typeof ServicesSiteIdentificationWorksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/site-survey-layout-execution': {
      id: '/services/site-survey-layout-execution'
      path: '/services/site-survey-layout-execution'
      fullPath: '/services/site-survey-layout-execution'
      preLoaderRoute: typeof ServicesSiteSurveyLayoutExecutionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/storm-water-drainage': {
      id: '/services/storm-water-drainage'
      path: '/services/storm-water-drainage'
      fullPath: '/services/storm-water-drainage'
      preLoaderRoute: typeof ServicesStormWaterDrainageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/tree-plantation-landscaping': {
      id: '/services/tree-plantation-landscaping'
      path: '/services/tree-plantation-landscaping'
      fullPath: '/services/tree-plantation-landscaping'
      preLoaderRoute: typeof ServicesTreePlantationLandscapingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/underground-sewerage-ugd-works': {
      id: '/services/underground-sewerage-ugd-works'
      path: '/services/underground-sewerage-ugd-works'
      fullPath: '/services/underground-sewerage-ugd-works'
      preLoaderRoute: typeof ServicesUndergroundSewerageUgdWorksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/water-pipeline-networks': {
      id: '/services/water-pipeline-networks'
      path: '/services/water-pipeline-networks'
      fullPath: '/services/water-pipeline-networks'
      preLoaderRoute: typeof ServicesWaterPipelineNetworksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/water-supply-line-installation': {
      id: '/services/water-supply-line-installation'
      path: '/services/water-supply-line-installation'
      fullPath: '/services/water-supply-line-installation'
      preLoaderRoute: typeof ServicesWaterSupplyLineInstallationRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  PrivacyPolicyRoute: PrivacyPolicyRoute,
  TermsConditionsRoute: TermsConditionsRoute,
  ProjectsIdRoute: ProjectsIdRoute,
  ProjectsFarmlandDevelopmentRoute: ProjectsFarmlandDevelopmentRoute,
  ProjectsPlottedDevelopmentRoute: ProjectsPlottedDevelopmentRoute,
  ServicesArchitecturalPlanningRoute: ServicesArchitecturalPlanningRoute,
  ServicesCompoundWallConstructionRoute: ServicesCompoundWallConstructionRoute,
  ServicesElectricalInfrastructureRoute: ServicesElectricalInfrastructureRoute,
  ServicesEndToEndLandDevelopmentRoute: ServicesEndToEndLandDevelopmentRoute,
  ServicesEntranceArchDesignConstructionRoute:
    ServicesEntranceArchDesignConstructionRoute,
  ServicesFarmlandDevelopmentRoute: ServicesFarmlandDevelopmentRoute,
  ServicesFootpathPaverInstallationRoute:
    ServicesFootpathPaverInstallationRoute,
  ServicesInternalRoadsRoute: ServicesInternalRoadsRoute,
  ServicesLandLevelingSitePreparationRoute:
    ServicesLandLevelingSitePreparationRoute,
  ServicesLandscapeTreePlantationRoute: ServicesLandscapeTreePlantationRoute,
  ServicesParkDevelopmentRoute: ServicesParkDevelopmentRoute,
  ServicesPlottedDevelopmentRoute: ServicesPlottedDevelopmentRoute,
  ServicesRccDrainageWorksRoute: ServicesRccDrainageWorksRoute,
  ServicesRoadDevelopmentWorksRoute: ServicesRoadDevelopmentWorksRoute,
  ServicesSiteIdentificationWorksRoute: ServicesSiteIdentificationWorksRoute,
  ServicesSiteSurveyLayoutExecutionRoute:
    ServicesSiteSurveyLayoutExecutionRoute,
  ServicesStormWaterDrainageRoute: ServicesStormWaterDrainageRoute,
  ServicesTreePlantationLandscapingRoute:
    ServicesTreePlantationLandscapingRoute,
  ServicesUndergroundSewerageUgdWorksRoute:
    ServicesUndergroundSewerageUgdWorksRoute,
  ServicesWaterPipelineNetworksRoute: ServicesWaterPipelineNetworksRoute,
  ServicesWaterSupplyLineInstallationRoute:
    ServicesWaterSupplyLineInstallationRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
